apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: liveness-http
spec:
  containers:
  - name: live-readi-container
    image: nginx
    volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
        - name: healthz-started
          mountPath: /usr/share/nginx/html/
  volumes:
  - name: config
    configMap:
      name: nginx-conf
  - name: healthz-started
    projected:
      sources:
      - configMap:
          name: healthz
          items:
            - key: healthz
              path: healthz
      - configMap:
          name: started
          items:
            - key: started
              path: started